<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWxQN2KL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWxQN2KL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWxQN2KL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWxQN2KL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWxQN2KL\App_KernelDevDebugContainer([
    'container.build_hash' => 'WxQN2KL',
    'container.build_id' => '7646dd0b',
    'container.build_time' => 1731863615,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWxQN2KL');
